### ISSUE TITLE
Documentation for running from the commandline?

### ISSUE THREAD

**Issue by mzealey** [theinvisible/openfortigui#83]
Looking at `ps` output it seems like I can probably run the vpn tunnel from command-line like:

```
/usr/bin/openfortigui --start-vpn --vpn-name blah --main-config /home/mark/.openfortigui/main.conf
```

Can this be documented somewhere rather than having to use gui to start/stop vpns?

**Comment by theinvisible** [comment]
Hi, yes thats possible but is not a main feature. If you want a CLI version to connect to Fortigate please use openfortivpn. Also there can be crashes because the process tries to connect to the main/parent process which doesnt exist in this case. Maybe its possible in the feature but has very low priority.
